apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWHVSN00xOWp2ZTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1EWXdPVEUwTkRsYUZ3MHpOakF4TURRd09URTVORGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURrTnc4Q2ZkaVRERGwrM21OQTBiSi9wNm1Xa0FHZldMdWZraTlRbG5rV0pRUVExTUZ4Y05NcGNtWHEKbTZNNmtBOWpxZytkNWl1TG5NcUFvV29JTWtlZHVZL1NPOW5qT2NBN0xsOExqN05JbkY4elBPYnEweklDR2g4SwpYRzM2aEJWZU1zdDNiU3JJSE1tVmdIVmIzRk9kTW81bkQwVHk4Nm5NTjVuQkhMRlhBOTIyb0dMdFU2cXpHblYrCkxsTHdDbDlFbVcwK3ozQ2VBVm5BRE81anJjenN6ekRZb0VkeDlhZ0JPMXlVVEFjMmw3MERIem9XMWNrbVhtWEoKd2cxemNUcmhnUVQzRDJjcldCWFk1OGlENmVZbFg3emdDVm9wR3pXQlZYSTkySVU0MWQ3YXo2Tlk5WkM5dGdIQwpVczJLQ2hBdUhvK3JlWWJHOXZQeVJoQ0hmdmlaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNFRLTksyNUZMbjk3WG4rMXFhSXpXblFVbFdqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRERSQUpESWltVwpwMmVFQzBpeWl6d3loeTZWRzV3TnpqRWFzYkxLQ1VpV281SEJodUtacmI2VTZLUUgvMUtxMnU2bkRLUVdNN1E0CkVqVzRFZFRvNUhEcDA2aTRFQmwxb1R1M0NUSDc0Q3VBTUxvRUtESnhWUTB3ckdRZzFrN2NIK3lkYWZkRWlyQ3QKVzIwblBwemNhZkxOTU9Oc1BUUCs3cDRFR0kwN3V1MU9adnpNL0hmNmlUTUFiYmQ5c3ErSmF1N21Ib2k2QTNaNgprbDFzbTV5L2JEWDlVUnZ1RHlYcFd4RW4rVzR3Z0R2QmNveTdCd0RCTEs1Vmw3MHg3TWNZN0NaMmtoaWJOeDJBCnBIQnBkMXlsaTVBZVliaDBtRTBFTTRQUDh0UWJkNjZYRWgxbWFKL2NYK2tEQlpTaWdwc1YyZGtkNXh5a3ZlU0MKcGNuRi9iTXIrelRXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://011B38A94A07823704FD1BA7E03A3AF2.gr7.us-east-1.eks.amazonaws.com
  name: shopeasy-dev-cluster.us-east-1.eksctl.io
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWHVSN00xOWp2ZTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1EWXdPVEUwTkRsYUZ3MHpOakF4TURRd09URTVORGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURrTnc4Q2ZkaVRERGwrM21OQTBiSi9wNm1Xa0FHZldMdWZraTlRbG5rV0pRUVExTUZ4Y05NcGNtWHEKbTZNNmtBOWpxZytkNWl1TG5NcUFvV29JTWtlZHVZL1NPOW5qT2NBN0xsOExqN05JbkY4elBPYnEweklDR2g4SwpYRzM2aEJWZU1zdDNiU3JJSE1tVmdIVmIzRk9kTW81bkQwVHk4Nm5NTjVuQkhMRlhBOTIyb0dMdFU2cXpHblYrCkxsTHdDbDlFbVcwK3ozQ2VBVm5BRE81anJjenN6ekRZb0VkeDlhZ0JPMXlVVEFjMmw3MERIem9XMWNrbVhtWEoKd2cxemNUcmhnUVQzRDJjcldCWFk1OGlENmVZbFg3emdDVm9wR3pXQlZYSTkySVU0MWQ3YXo2Tlk5WkM5dGdIQwpVczJLQ2hBdUhvK3JlWWJHOXZQeVJoQ0hmdmlaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNFRLTksyNUZMbjk3WG4rMXFhSXpXblFVbFdqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRERSQUpESWltVwpwMmVFQzBpeWl6d3loeTZWRzV3TnpqRWFzYkxLQ1VpV281SEJodUtacmI2VTZLUUgvMUtxMnU2bkRLUVdNN1E0CkVqVzRFZFRvNUhEcDA2aTRFQmwxb1R1M0NUSDc0Q3VBTUxvRUtESnhWUTB3ckdRZzFrN2NIK3lkYWZkRWlyQ3QKVzIwblBwemNhZkxOTU9Oc1BUUCs3cDRFR0kwN3V1MU9adnpNL0hmNmlUTUFiYmQ5c3ErSmF1N21Ib2k2QTNaNgprbDFzbTV5L2JEWDlVUnZ1RHlYcFd4RW4rVzR3Z0R2QmNveTdCd0RCTEs1Vmw3MHg3TWNZN0NaMmtoaWJOeDJBCnBIQnBkMXlsaTVBZVliaDBtRTBFTTRQUDh0UWJkNjZYRWgxbWFKL2NYK2tEQlpTaWdwc1YyZGtkNXh5a3ZlU0MKcGNuRi9iTXIrelRXCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://011B38A94A07823704FD1BA7E03A3AF2.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:348823728691:cluster/shopeasy-dev-cluster
contexts:
- context:
    cluster: shopeasy-dev-cluster.us-east-1.eksctl.io
    user: Khushal@shopeasy-dev-cluster.us-east-1.eksctl.io
  name: Khushal@shopeasy-dev-cluster.us-east-1.eksctl.io
- context:
    cluster: arn:aws:eks:us-east-1:348823728691:cluster/shopeasy-dev-cluster
    user: arn:aws:eks:us-east-1:348823728691:cluster/shopeasy-dev-cluster
  name: arn:aws:eks:us-east-1:348823728691:cluster/shopeasy-dev-cluster
current-context: arn:aws:eks:us-east-1:348823728691:cluster/shopeasy-dev-cluster
kind: Config
users:
- name: Khushal@shopeasy-dev-cluster.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - shopeasy-dev-cluster
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
- name: arn:aws:eks:us-east-1:348823728691:cluster/shopeasy-dev-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - shopeasy-dev-cluster
      - --output
      - json
      command: aws