apiVersion: v1
kind: Service
metadata:
  name: shopeasy-service
  labels:
    app: shopeasy
spec:
  type: LoadBalancer
  selector:
    app: shopeasy
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
